name: Check Upstream Release and Publish

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch: # 支持手动触发

jobs:
  check-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout your repo
        uses: actions/checkout@v4

      # 2. 获取最新的上游发布版本
      - name: Get latest upstream release
        id: get_release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/lich0821/WeChatFerry/releases/latest | jq -r .tag_name)
          echo "latest_release=$LATEST_TAG" >> $GITHUB_ENV

      # 3. 获取本地版本号
      - name: Read local version
        id: get_local_version
        run: |
          LOCAL_VERSION=$(jq -r .version packages/core/src/version.json)
          echo "local_version=$LOCAL_VERSION" >> $GITHUB_ENV

      # 4. 比较版本
      - name: Compare versions
        id: compare
        run: |
          echo "latest_release=${{ env.latest_release }}"
          echo "local_version=${{ env.local_version }}"
          if [ "${{ env.latest_release }}" != "${{ env.local_version }}" ]; then
            echo "Versions are different, new version available."
            echo "new_version=true" >> $GITHUB_ENV
          else
            echo "Versions are the same, no new version."
            echo "new_version=false" >> $GITHUB_ENV
          fi

      # 5. 如果没有新版本，退出并输出当前版本
      - name: Exit if no new version
        if: env.new_version == 'false'
        run: |
          echo "No new version detected. Current version is ${{ env.local_version }}. Skipping publish."

      # 6. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 7. 安装 pnpm
      - name: Install pnpm globally
        run: |
          npm install -g pnpm@8
          pnpm --version  # 确认 pnpm 安装成功

      # 8. 安装依赖
      - name: Install dependencies
        if: env.new_version == 'true'
        run: pnpm install

      # 9. 设置 .npmrc 配置以便发布
      - name: Setup .npmrc for publish
        if: env.new_version == 'true'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./.npmrc
          cat ~/.npmrc  # 输出 .npmrc 文件内容进行调试
          ls -l  # 输出当前目录文件列表进行调试

      # 10. 更新 version.json
      - name: Update version.json
        if: env.new_version == 'true'
        run: |
          jq --arg ver "${{ env.latest_release }}" '.version = $ver' packages/core/src/version.json > tmp.json && mv tmp.json packages/core/src/version.json

      # 11. 验证 NPM token 是否有效
      - name: Verify NPM token
        if: env.new_version == 'true'
        run: |
          echo "Verifying NPM token..."
          npm whoami  # 验证 token 是否有效

      # 12. 发布 core 包
      - name: Core package build & publish
        if: env.new_version == 'true'
        run: |
          cd packages/core
          pnpm run get-wcf
          pnpm run build-proto
          pnpm version patch
          git add .
          pnpm publish --access public --no-git-checks  # 禁用 git 检查，避免 "unclean" 错误

      # 13. 发布 CLI 包
      - name: CLI package build & publish
        if: env.new_version == 'true'
        run: |
          cd packages/cli
          pnpm version patch
          git add .
          pnpm run build
          pnpm publish --access public --no-git-checks  # 禁用 git 检查，避免 "unclean" 错误

      # 14. 提交并推送更新
      - name: Commit and push changes
        if: env.new_version == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: update version to ${{ env.latest_release }}"  # 提交更新
          git push

      # 15. 为提交打标签
      - name: Tag the commit with release version
        if: env.new_version == 'true'
        run: |
          git tag ${{ env.latest_release }}  # 为提交添加 release 版本标签
          git push origin ${{ env.latest_release }}  # 推送标签到远程
